### ISSUE TITLE
[BUG] Unable to use UI 

### ISSUE THREAD

**Issue by ahalbert** [getdevspace/open-management#12]
Hi, I opened DevSpace, and it started successfully. On startup, it showed me the wiki, and the invited me to import projects using a + button. I attempted to do this, and a file dialog popped up. However, when I expanded /home - it wouldn't show me anything. (See screenshot) I quit the app and restarted.

When I started up again, it went to the main UI, but only two buttons are enabled (see screenshot)
The + button for importing projects no longer does anything when I click on it. 
The button that goes to the "Send Feedback/Report Bug/Wiki" menu works. 

<img width="1207" alt="Screen Shot 2020-05-22 at 4 15 48 PM" src="https://user-images.githubusercontent.com/849804/82706640-19a45580-9c48-11ea-9024-eba53058405f.png">
<img width="646" alt="Screen Shot 2020-05-22 at 10 44 46 AM" src="https://user-images.githubusercontent.com/849804/82706641-19a45580-9c48-11ea-9851-02e58b27e07d.png">

**Comment by gabrielgatu** [comment]
Hey @ahalbert, thanks for the report! Could I ask you to try 2 things out?
1: If you try to expand any other folder, does it work?
2: Could you try to expand the folder called Users/<your-logged-user-name>/, does it work?

**Comment by ahalbert** [comment]
Gabriel, 

Sorry for the delay. I can't actually import projects anymore. The "+" icon works. Though I realize now I forgot /home isn't a thing on OS X.

**Comment by gabrielgatu** [comment]
Yeah, I think your DevSpace installation expired since it has an automatic and internal countdown of 7 days for all beta testers, starting from the first launch.

I'll finally use the free time I'm gonna have this weekend to rework on the import panel and hopefully migrate it from the custom to the default one provided by electron, which is going to make things clearer for users, plus it doesn't require knowledge of os filesystem's structure.

The new version should be available on monday, I'm gonna ping you when I'm done :)

**Comment by gabrielgatu** [comment]
New version here :tada: 
It brings the new native import panel, used both for projects and assets. It should be easier to use now. Minor bugs have been resolved as well, and the beta period has been extended to 30 days from first activation.

As always, downloads available here: https://github.com/getdevspace/open-management/releases/tag/v1.0.0-beta1

@ahalbert Could you give it a try please?

**Comment by ahalbert** [comment]
@gabrielgatu - I still have the same problem. Do I need to uninstall the app and then use the new release? I just downloaed the new installer and ran it, then ran the app again

**Comment by gabrielgatu** [comment]
I've tried myself installing the app again on MacOS and indeed don't know why, but I need to make sure all previous copies are deleted from the system before installing the new one. Can you try that as well?

Finally, just to make sure, can you also delete the config directory of DevSpace? On macOS it is located at: $HOME/Library/Preferences/devspace.
Just run: `rm -rf $HOME/Library/Preferences/devspace` and you should be good to go.
In case of Linux: `rm -rf $HOME/.config/devspace`.

**Comment by ahalbert** [comment]
Fixed, Thanks
